In [132]:
import pandas as pd
import numpy as np

In [133]:
pd.set_option('display.max_columns', None)

In [134]:
data = pd.read_csv('./html2023-spring-final-project/train.csv')

##### License and Oficial Video
They both are mostly the same
If license has true/false then oficial video = true/false
if license or oficial_video is empty then False


Convert False to 0 and True to 1

In [135]:
data['Licensed'].fillna(data['official_video'], inplace=True)
data['Licensed'].fillna(False, inplace=True)

data['Licensed'].replace({True: 1, False: 0})

data['official_video'].fillna(data['Licensed'], inplace=True)
data['official_video'].fillna(False, inplace=True)

data['official_video'].replace({True: 1, False: 0})


0        0
1        0
2        0
3        1
4        1
        ..
17165    1
17166    1
17167    1
17168    1
17169    1
Name: official_video, Length: 17170, dtype: int64

##### Fill nan data in 'Energy', 'Key', 'Loudness', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo', 'Duration_ms' by Danceability

In [136]:
def fillOptions(data, option = 'max'):
    if option == 'max':
        return data.value_counts().idxmax()
    elif option == 'mean':
        return data.mean()
    elif option == 'median':
        return data.median()


In [137]:
danceabilityUnique = data['Danceability'].unique()
danceabilityUnique

array([0., 1., 4., 6., 5., 3., 2., 9., 8., 7.])

In [145]:
dataFill = ['Energy', 'Loudness', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo']

In [139]:
newData = pd.DataFrame(columns=data.columns)
for i in danceabilityUnique:
    dance = data[data['Danceability'] == i]

    for info in dataFill:
        max = fillOptions(dance[info], option = 'max')
        dance[info].fillna(max, inplace = True)

    newData = newData.append(dance)


C:\Users\Miguel\AppData\Local\Temp\ipykernel_15224\4157290635.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dance[info].fillna(max, inplace = True)
C:\Users\Miguel\AppData\Local\Temp\ipykernel_15224\4157290635.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dance[info].fillna(max, inplace = True)
C:\Users\Miguel\AppData\Local\Temp\ipykernel_15224\4157290635.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dance[info].filln

In [150]:
dataArtist = newData['Artist'].unique()
dataArtistMarshmello = newData[newData['Artist'] == 'Marshmello']

In [152]:
dataArtistMarshmello['Composer'].unique()

array([nan, 'Yeti Beats', "Finneas O'Connell", 'Louis Bell', 'Juicy J',
       'Mike Dean', 'Terrace Martin', 'Noah "40" Shebib', 'Ricky Reed',
       'Ludwig Göransson', 'J. Cole'], dtype=object)

In [39]:
filteredDataByDanceability = data[data['Danceability'] == 9]

In [95]:
majority_value = filteredDataByDanceability['Energy'].value_counts().idxmax()
majority_value
# # Replace NaN values with the majority value
filteredDataByDanceability['Energy'].fillna(majority_value, inplace=True)

C:\Users\Miguel\AppData\Local\Temp\ipykernel_15224\889643387.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filteredDataByDanceability['Energy'].fillna(majority_value, inplace=True)


In [101]:
filteredDataByDanceability.isnull().sum()

Danceability          0
Energy                0
Key                 230
Loudness            256
Speechiness         234
Acousticness        230
Instrumentalness    247
Liveness            221
Valence             247
Tempo               235
Duration_ms         263
Views               242
Likes               243
Stream              234
Album_type          248
Licensed              0
official_video        0
id                    0
Track               232
Album               235
Uri                 238
Url_spotify         258
Url_youtube         230
Comments            227
Description         235
Title               249
Channel             256
Composer            241
Artist              242
dtype: int64

In [45]:
filteredDataByDanceability['Energy'].median()

0.267089984

In [46]:
filteredDataByDanceability['Loudness'].median()

-6.1555

In [47]:
filteredDataByDanceability['Loudness'].mean()

-6.553415593705293

In [48]:
filteredDataByDanceability['Loudness'].value_counts().idxmax()

-5.522

In [154]:
data['Key'].unique()

array([ 3.,  7.,  6., nan,  5., 10.,  1.,  2.,  0.,  4.,  8.,  9.])

In [155]:
data['Album_type'].unique()

array(['album', nan, 'single', 'compilation'], dtype=object)

In [157]:
data['Composer'].unique()

array([nan, "Finneas O'Connell", 'Louis Bell', 'Juicy J',
       'Noah "40" Shebib', 'Mike Dean', 'Yeti Beats', 'Terrace Martin',
       'Ludwig Göransson', 'Ricky Reed', 'J. Cole'], dtype=object)

In [158]:
data['Artist'].unique()

array(['Marshmello', 'Bon Iver', 'Kamasi Washington', 'Drake',
       'Alicia Keys', 'Major Lazer', 'J. Cole', 'Flume', 'Tame Impala',
       nan, 'Chance the Rapper', 'Kanye West', 'deadmau5', 'Rihanna',
       'Dua Lipa', 'The Chainsmokers', 'Billie Eilish', 'Soccer Mommy',
       'Sufjan Stevens', 'Parquet Courts', 'Phoebe Bridgers',
       'Mac DeMarco', 'Disclosure', 'Tyler, The Creator', 'Black Midi',
       'Charli XCX', 'Julien Baker', 'Grimes', 'Pharrell Williams',
       'Khruangbin', 'Alt-J', 'The 1975', 'Vampire Weekend', 'Halsey',
       'Big Thief', 'Justin Bieber', 'Robyn', 'Shawn Mendes', 'Mitski',
       'Anderson .Paak', 'Angel Olsen', 'Fontaines D.C.', 'Justice',
       'Skrillex', 'Swedish House Mafia', 'Kurt Vile', 'Travis Scott',
       'The Weeknd', 'Avicii', 'SZA', 'FKA twigs', 'Jay-Z', 'Lizzo',
       'Cardi B', 'Moses Sumney', 'Carly Rae Jepsen', 'Foals',
       'David Guetta', 'Bruno Mars', 'King Gizzard & The Lizard Wizard',
       'Lorde', 'St. Vincent', 'L

In [159]:
len(data['Artist'].unique())

97